title: GEMS Innovation Week 2020
author: GEMS Singapore Student Council
email: your-email@domain.com
description: >
  GEMS Singapore Student Council is proud to be hosting the school’s first 
  Innovation Week from February 5th to February 14th. We will be having a 
  variety of events throughout the week for students to showcase their talents 
  as well as develop new ones. They’re will be an event for everyone!
show_excerpts: true
baseurl: /innovationweek2020

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Innovation Week 2020
  tagline: Learn, Build, Pitch
  secondtagline: GEMS Singapore Student Council
  date_format: "%b %-d, %Y"
  style: blue

  social_links:
    instagram: gemsstucosg
    github:  gemssingaporestudentcouncil
    rss: rss

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true


